# Site settings
title: Music Pro
email: musicpro@musicpro.ge
description: "Wow such meta, much description, very music"
baseurl: ""
url: "http://musproject.github.io"

# Build settings
markdown: kramdown
permalink: pretty
